export const debugUI = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Durable agent memory</title><style>
body{font:16px system-ui;max-width:1000px;margin:40px auto;padding:0 20px;background:#f5f6f8;color:#172033}input,textarea,button,select{font:inherit;padding:10px;margin:5px}textarea{display:block;width:90%;height:90px}button{cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:white;padding:20px;border:1px solid #ccd2de}small{display:block}
</style></head><body><h1>Durable agent memory</h1><p>Pi transcript ≠ long-term memory ≠ retrieved working context.</p><p>Memory writes append durable data. Retrieved evidence is frozen at the tail of a new Pi turn.</p>
<label>API token <input id="token" type="password" autocomplete="off"></label><label>Agent <input id="agent" value="demo"></label><small>The token stays in this page's memory. All debug APIs require it.</small>
<textarea id="text">My favourite database for small projects is SQLite.</textarea><label>Kind <select id="kind"><option>preference</option><option>decision</option><option>fact</option><option>observation</option></select></label>
<div><button data-action="remember">Remember</button><button data-action="chat">Chat with Pi</button><button data-action="search">Search L0</button><button data-action="context">Build context</button><button data-action="compact">Finish summaries</button><button data-action="reset">New cache epoch</button><button data-action="debug">Inspect all</button></div>
<label>Source ID <input id="source" size="55"></label><button data-action="read">Read L1/L2</button><button data-action="expand">Expand children</button><pre id="output">Write a preference, finish summaries, start a new epoch, then ask: What database would I probably choose here?</pre>
<script>
const get=id=>document.getElementById(id);document.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const action=b.dataset.action,text=get('text').value;const body=action==='remember'?{content:text,kind:get('kind').value,namespace:'preferences',idempotencyKey:crypto.randomUUID()}:action==='chat'?{message:text,operationId:crypto.randomUUID()}:action==='context'?{query:text,maxTokens:4000}:action==='search'||action==='reset'?{query:text}:{};const isGet=['debug','read','expand'].includes(action);get('output').textContent='Working…';try{const response=await fetch('/api/'+encodeURIComponent(get('agent').value)+'/'+action+(action==='read'||action==='expand'?'?id='+encodeURIComponent(get('source').value):''),{method:isGet?'GET':'POST',headers:{'content-type':'application/json','authorization':'Bearer '+get('token').value},...(isGet?{}:{body:JSON.stringify(body)})});get('output').textContent=JSON.stringify(await response.json(),null,2)}catch{get('output').textContent='Request failed'}});
</script></body></html>`;
